---
title: "Foundations of Functional Programming with purrr"
author: "Miao Cai^[Department of Epidemiology and Biostatistics, College for Public Health and Social Justice, Saint Louis University. Email: [miao.cai@slu.edu](miao.cai@slu.edu)]"
date: "1/10/2019"
output:
  html_document:
    theme: yeti
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: show
  pdf_document:
    number_sections: yes
link-citations: yes
link-color: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simplify iterations and lists with purrr

`map(object, function)`

- object: can be a vector or list
- function: any function in R that takes the input offered by the object

`map(survey_data, ~nrow(.x))`

`map_dbl` outputs a vector as the output:
`map_dbl(survey_data, ~nrow(.x))`


`map_lgl` outputs a vector of logical values as the output:
`map_lgl(survey_data, ~nrow(.x)==14)`


`map_chr`
```{r}
# Map over species_names list
map_chr(species_names, ~.x)
```

