LITERATURE REVIEW
=================
Naturalistic driving Study (NDS)
--------------------------------
Traditional truck crash prediction studies almost exclusively use data that ultimately trace back to post hoc vehicle inspection, interviews with survived drivers and witnesses, and police reports [@hickman2018synthetic; @stern2019data]. Despite these data can be in-depth and thorough, they have several inherent limitations. Firstly, truck crashes are extremely rare compared with non-crashes. According to the @fmcsareport2017, large truck and bus fatalities in 2017 were 0.156 per million travelled vehicle miles, which was a 6.8 percent increase from 2016. This rareness poses a challenge to infer unbiased estimates using traditional statistical models [@guo2010near; @theofilatos2018impact]. Secondly, most truck crash data reply on post hoc police reports. Although these data are generally accurate and detailed by police officers, they are limited in determining the information of the driver in the meaningful time period leading up to the crash [@dingus2011estimating]. Some of the critical factors, such as distraction, are not reported or cannot be determined due to a varitety of reasons [@dingus2011estimating], and these data were subject to recall bias even if they were reported. Thirdly, truck crashes are under-reported, particularly for no-injury and minor-injury crashes [@ye2011investigation; @stern2019data]. It is estimated that 25% of minor-injury and 50% of non-injury crashes were not reported, while 100% of fatal crashes were reported [@savolainen2011statistical].

In light of the aforementioned limitations, a growing number of naturalistic driving studies have been initiated worldwide to identify crash causation and develop effective action to improve traffic safety [@klauer2009comparing; @hickman2018synthetic; @guo2019statistical], such as the 100-Car NDS by the Virginia Tech Transportation Institute [@dingus2006100], the second Strategic Highway Research Program including more than 3,400 drivers [@ghasemzadeh2017probit], and the UDRIVE NDS in Europe [@eenink2014udrive; @barnard2016study]. There are also a few other NDS that target at specific sub-populations, such as the 40-Teen NDS [@alden2016animal], the Older Driver Fitness-to-Drive NDS [@guo2015older], and the Commercial Truck Driver NDS [@sparrow2016naturalistic]. 

NDS use unobstrusive devices, sensors, and cameras installed on vehicles to proactively collect  frequent naturalistic driving behavior and and performance data under real-world driving conditions [@hickman2018synthetic; @guo2019statistical]. Compared with tradtional post-hoc crash data that are road segment-based, NDS collect driver-based data which are more useful in comparing the rate of unsafe events under different circumstances. In addition, NDS data provide high-resolution driver behavior and performance data, which enable researcher to access data shortly prior to the occurance of crashes or SCE without information bias or selection bias [@guo2010near]. Third, collecting naturalistic data is considerably less costly and difficult per observation compared to tradtional crash data that involve human resource, interviews, and witnesses, so NDS generally collect a large amount of data, which creates both an opportunity and a challenge to researchers. @guo2019statistical provides an excellent review that compares empirical , naturalistic, and epidemiological data collection methods in traffic safety research.

The first large-scale NDS was The 100-Car Naturalistic Driving study conducted in North Virginia, the United States [@neale2005overview]. The research team continuously followed the 102 recruited drivers for 12 months, resulting in two million miles and over 40,000 hours of driving data. To maximize the number of SCEs, the research team intentionally chose more young drivers and high mileage drivers. Based on this data, @dingus2006100 found that hard braking events were significantly associated with collisions and near-crashes. Since the number of near-crashes and incidents were significantly larger than crashes, they proposed to use near-crashes and incidents as surrogates of crashes.

Safety-critical events (SCEs)
-----------------------------

Instead of collecting extremely rare vehicle crash data, NDS focus on safety-critical events (SCEs) and near-crash events, defined as events that used last-second successful evasive maneuver that avoided crashes [@dingus2011estimating]. Although near-crashes or SCEs were not real crashes, these studies suggested that they are highly correlated with crashes [@dingus2006100; @guo2010near; @dingus2011estimating]. The most commonly studied SCE is hard brakes (also knowns as hard-braking events or harsh braking), defined as a deceleration force higher than a pre-specified threshold, such as 0.3 g [@jansen2018harsh; @mollicone2019predicting].

A more formal definition of near-crash, or the more general accident precursor, in safety analysis and accident prevention field was proposed and analyzed in @saleh2013accident. An accident precursor was defined as a chain of adverse events following an initial off-nominal event, which can result in an accident if compounded with additional adverse conditions [@saleh2013accident]. A near-crash or near miss is a special case of accident precursor, with the feature of being close to a complete accident sequence. Accidence precursor has been widely studies in certain safety science in which the accidents are extremely rare, such as nuclear industry [@smith2007decision], chemistry [@phimister2003near], and aerospace industry [@kirwan2008human]. 

<!--
@wu2013defining \hl{defined crash surrogates in naturalistic driving data.}
-->

The rationale for using near-crashes and SCEs as surrogates for crashes is Heinrich's Triangle. The Heinrich's Triangle assumes that less severe events are more frequent than severe events, and the frequency of severe events can diminish as that of less severe events decreases [@guo2019statistical]. The latter assumption can be quantitatively tested using crash and naturalistic driving data, but verifying the former assumption is challenging since the causal mechanism is complex and unknown [@guo2010near]. Applying SCEs in traffic safety studies to this Heinrich's Triangle can substantially increase the study sample size and may potentially enable the estimation of driving risk. However, a crucial question prior to the usage of SCEs in naturalistic studies is whether they are good surrogates of traffic crashes.

@guo2010near proposed two critical principles for using near crashes as surrogates for crashes: 1) similar or the same causal mechanisms between crashes and surrogates, 2) a strong association between the frequency of surrogates and crashes. Based on the 100-car database, they investigated the two principles using a sequential factor analysis, a Poisson regression, and a sensitivity analysis. The study concluded that using near crashes as surrogates for crashes will lead to conservative risk estimates but significantly reduce the variance of estimation. They suggested that using near crashes as surrogates in small-scale studies will be informative for evaluating the risk of crashes.

Crashes and SCEs
----------------

@gordon2011analysis conducted a preliminary study to validate surrogates for road-departure crashes by spatially merging road geometry, average traffic, crashes, and naturalistic driving data. Bayesian seemingly unrelated Poisson models estimated with weighted least squares were used to examine if the same sets of predictor variables can have the same effects on crashes and surrogates respectively. The found that time to edge crossing and lane-departure warning were two useful surrogates for crashes on rural nonfreeway roads, while lane deviation was a poor surrogate for lane-departure crashes.

@simons2012elevated examined whether elevated gravitational-force predicts crashes and near crashes among 42 newly licensed teenage drivers in Virginia. The study used the Naturalistic Teenage Driving Study that followed the recruited drivers for 18 months. A logistic regression estimated with generalized estimating equations to account for the within-subject correlation among different months. It was found that the rate of elevated gravitational-force events was positively associated with the rate of crashes and near-crashes (odds ratio = 1.07, 95% confidence interval: 1.02, 1.12), with the area under curve (AUC) value of 0.76.

@wu2012crashes proposed a conceptual framework to estimate the crash-to-surrogate ratio $\pi$ and used the 100-Car study to test the framework. The study found that the conditional probability of a crash was increased by 24 times with a lateral acceleration more than 0.7 g, but the probability was decreased by other factors such as the event occurring in daylight and dry pavement. A later study by @wu2013defining developed diagnostic procedures to screen crashes and near misses under naturalistic study settings. The study applied the 100-Car Natural Driving Study on the proposed framework and identified three conditions to define surrogate events: 1) maximum lateral acceleration difference of no smaller than 0.4 g, 2) non-intersection related, and 3) maximum lateral acceleration difference no smaller than 0.9 per event or between 0.8 and 0.9 g during night time.

@guo2013individual attempted to identify risk factors of driving at drivers level and predict high-risk drivers based on the 100-Car study. The study used a negative binomial regression to examine the potential four risk factors of crashes and near-crashes. Besides, they used a K-mean clustering to classify the drivers into high-, moderate-, and low-risk groups based on crash and near-crash rates, and applied two logistic regressions to predict high- or moderate-risk drivers. The results confirmed that critical-incident event rates were significantly associated with individual driving risk. The two logistic regressions high achieved AUC values of 0.938 and 0.93. They also highlighted that it was a first-step study and more studies with larger and representative data were needed to confirm the association. A similar study by @wu2014using also used the 100-Car study. This study used a Bayesian multivariate Poisson log-normal model to simultaneously account for crash frequency and severity. They also found a significant positive association between crashes, near crashes, and crash-relevant incidents.

@pande2017preliminary used linear referencing to link Global Positioning System (GPS) data with roadway features on 39 segments of Highway 101 in California. Negative binomial models and random-effects negative models account for segment-specific variance were used to investigate the relationship between historic crashes and hard braking. It was found that the freeway segments with high hard braking rates also had higher long-term crash rates, although the other three explanatory variables, average daily traffic, the presence of horizontal curvature and auxiliary lanes were not statistically significant. 

@gitelman2018exploring used in-vehicle data recorders (IVDR) data collected on 3500 segments of interurban roads in Israel to examine the association between two types of safety-related events (braking and speed alert) and crashes on different road types. Negative binomial models were applied to account for the over-dispersion in the data, and they also included a number of road infrastructure characteristics as covariates. The number of braking events was found to be positively associated with injury crashes on single- and dual-carriageway roads while the association was not significant on freeways. In contrast, they yield counterintuitive results that speed alert events (overspeed) were consistently and negatively associated with injury crashes on all road types. It was suggested that a speed alert event were not a good surrogate for crashes, possibly due to its rough definition.

However, NDS is not bought without a doubt. @knipling2015naturalistic challenged the validity of using naturalistic driving data and SCEs by stating that the purpose of traffic safety studies is to identify causes of crash harm and develop interventions. Crash harm is defined as property damage, injury, income lost, and all other consequences of different severities [@zaloshnja2007unit]. NDS often use SCEs as surrogates of crashes, but very few or no crashes, let alone human harm. Therefore, @knipling2015naturalistic argues that SCEs are not an appropriate part of the Heinrich's Triangle and researchers generally cannot derive valid quantitative conclusions on causations of harm based on NDS datasets. 

Another study by @knipling2017threats specifically targeted Hour-of-Service rule research, such as @blanco2011impact and @hanowski2008analysis, and relevant policy revisions among commercial truck drivers. He argued that HOS studies with a quasi-experiment design were subject to confounding variables, so these studies are limited in demonstrating a causal relationship between HOS and safety outcomes. The paper also argued that NDS lacked external validity since no large truck NDS had examined the causal link between crashed and SCEs. Lastly, the construct validity was doubted as the relationship between driver fatigue, HOS, and SCEs had not been validated.

Risk factors for traffic safety
-------------------------------

### Fatigue

Fatigue has been the most pressing risk factor for truck crashes and SCEs. It is estimated by National Sleep Foundation that approximately 32% of drivers drive with fatigue over twice a month [@nsleepf]. The American Automobile Association Foundation for Traffic Safety claimed that 16.5% of fatal traffic accidents and 12.5% of injuries-related collisions were associated with driving with fatigue in 2010 [@aaafoundation]. The National Highway Traffic Safety Administration (NHTSA) estimated that 60% of fatal truck crashes were attributable to the driver falling asleep while driving [@craye2016multi; @cavuoto2017understanding]. The FMCSA estimated that the causal role of fatigue is around five times higher in fatal than in property damage truck crashes [@knipling2017threats]. 

Fatigue is often defined as a multidimensional process that leads to diminished worker performance, which may be a result of prolonged work, psychological, socioeconomic, and environment factors [@yung2016fatigue; @cavuoto2017understanding]. However, this definition has low specificity since there are other factors associated with a decreased worker performance, such as cell phone use, which does not result in driver fatigue. There is no uniform and succint definition on fatigue since it involves interactions between biological, behavior, and psychological process. A comprehensive review on fatigue definition and measurement is provided by @yung2016fatigue.

The mechanism of fatigue leading to traffic safety events is that the driver’s capability to stay alert to ambient traffic and pedestrians will be largely impaired. The reaction time is subsequently prolonged in that situation [@zhang2014study]. It is estimated that 17 hours of continuous working lead to a deterioration of driving performance equivalent to a blood alcohol level of 0.05% [@maclean2003hazards]. What makes the outcomes worse is that fatigue driving is more likely to happen on expressways and major highways where the speed limit is over 55 miles per hour [@knipling1994crashes]. This is especially concerning because fatigue driving safety critical events are more likely to result in serious injuries and fatalities, compared with non-fatigue driving safety critical events.

Although fatigue has been recognized as the primary reason for traffic safety, little has been done about drowsy driving since there is no simple way to objectively measure fatigue driving [@dement1997perils]. In view of the difficulty of measuring fatigue, researchers have attempted to use different proxies of fatigue associated with truck drivers, such as cumulative driving time, ocular and physiological metrics, sleep patterns, and night driving.

Cumulative driving time, has also been a measure of driver's fatigue level, especially among NDSs. For example, @nakayama2002trial found that there was a significant increase in the fatigue of drivers after 12 hours of continuous driving.  @jovanis2011hours used cumulative hours of driving, time of the day, driving patterns over multiple days, rests after driving, and the 34-hour recovery policy as measures of driver fatigue. They found that more driving time was associated with increased odds of crashes among 686 less-than-truck-load drivers (224 crash-involved drivers and 464 randomly sampled non-crash drivers from the same terminal in the same month), with the highest odds in the 11-th hour. From the fifth hour to the 11th hour, the odds of crashes were consistently increasing [@jovanis2012effects]. In contrast, @soccolich2013analysis found no significant difference in safety outcomes between the 11th driving hour and driving hours 8, 9, or 10 using from the Naturalistic Truck Driving Study data. Desipte the fact that working hours were not significant, they suggested an interaction between driving hours and working hours: a work day that starts with several hours of non-driving work and then followed by 14 hours of driving was significantly associated with risk of safety-critical events. Another study by @mollicone2019predicting used a Poisson regression to quantify the association between driver performance and predicted fatigue level based on natualistic driving data from 106 commercial truck drivers. The number of hard-braking events, defined as deceleration force greater than 0.3 g, were considered the outcome variable in that study. The fatigue level was predicted using a complex biomathematical model provided by @mccauley2013dynamic. After accounting for time of the day, they reported a significant association between predicted fatigue and the rate of hard-braking events (relative risk 1.078, 95% confidence interval 1.013-1.146).

Numerous studies used ocular metrics, such as eye closure and blinking patterns, to detect driver's fatigue [@golias2013evaluating]. For example, @jackson2016utility measured the eyelid closure of 22 healthy participants with 24 hours of sleep deprivation. They found a significant increase in proportions of time with closed eyeclids after the sleep deprivation, which were significantly associated with crashes, Psychomotor Vigilance Task lapses, and subjective sleepiness scores (95% confidence interval of Spearman's correlation coefficient was 0.46 to 0.69). Other studies used physiological measures, such as electroencephalogram (EEG) and heart rate, as indicators of fatigue [@golias2013evaluating]. It has been demonstrated that awake but drowsy truck drivers during working have increased alpha and theta power densities in EEG [@kecklund1993sleepiness; @cajochen1995power; @mitler1997sleep]. The variability of heart rates has been identified as passive proxy of fatigue among drivers [@mulder1992measurement; @patel2011applying].

Lack of sleep or specific sleep patterns have also been used as proxies of fatigue. For example, @chen2016influence used negative binomial regression to identify the association between four sleep patterns and driving performance based on the Naturalistic Truck Driving Study data. They revealed that shorter sleep, early-stage sleep in a non-work period, and insufficient sleep between 1 a.m. and 5 a.m. were associated with increased safety-critical event rates. @sparrow2016naturalistic reported that truck drivers with a retart break of only one nighttime period (defined as 1 a.m. to 5 a.m.) experienced more lapses of attention, elevated lane deviation at night, and higher sleepiness measured by subjective questionnaires. A naturalistic driving study by @wu2014using found that more sleeping hours was found to be beneficial to reduce near crashes.

A significant amount of research emphasizes the association between time of the day (such as night driving) and the development of fatigue [@cavuoto2017understanding]. Night drving is often accompanied by changes in shift scheduling, inadequate sleep, sleep apnea and disorder. For example, @pack1995characteristics reported that the crashes in which the drivers fell asleep occurred primarily from mid-night to 7 a.m. and from 2 p.m. to 4 p.m.. @mitler1997sleep monitored 80 truck drivers in North America using 24-hour electrophysiologic measures. They found that drivers an average had 5.18 hours of sleep in bed per day and 4.78 hours of electrophysiologically validated sleep per day, which were significantly less than needed to stay alert on job. It was also suggested that late-night or early-morning work were detrimental to the drivers' sleep. @pahukula2015time investigated the risk factors associated with crashes on Texas urban freeways between 2006 and 2010. They ran separate random-effects logistic regressions on five time periods: early morning (12 a.m. to 4 a.m.), morning (5 a.m. to 9 a.m.), mid-day (10 a.m. to 3 p.m.), afternoon (4 p.m. to 8 p.m.), and evening (9 p.m. to 11 p.m.). The results revealed major differences in traffic flow, light conditions, surface conditions, time of year, and the percentage of trucks on road among the five different models.

### Driver characteristics

Young and older drivers have been reported to have higher risk of crashes or SCEs. The reasons for these young drivers having higher risk of driving are not fully explained, but could largely be attributed to inexperience and reckless driving. In contrast, older drivers may find it difficult to adjust for the sleep-wake cycle to keep pace with the intense schedule required by the employer company, which may increase the likelihood to be sleepy or fatigued. @duke2010age reviewed published literature on age-related safety issues among professional heavy vehicle drivers. The review suggested a U-shaped relationship: the chance of driving safety issues declines before 27 years old, plateau until the age of 63, and starts to grow up again after 63.

Young drivers are much better in the sense of physical health and resistance to fatigue compared with aged drivers, however, they are more vulnerable regarding the experience of driving. @clarke2006young suggested that young drivers (17 – 19 years old), especially males, have significantly more accidents than other drivers during the hours of darkness, on rural curves, and rear-end shunts compared with male drivers aged 20 -25 years. @campbell1991fatal found that truck drivers under the age of 19 were over-involved in fatal accidents by a factor of 4, and those aged between 19 and 20 were over-involved by a factor of 6. @pack1995characteristics revealed that the drivers under the age of 25 accounted for 55% of the 4,333 crashes in which the drivers were judged to be asleep whiling driving. @otmani2005sleepiness tested the sleepiness of 36 profession drivers in simulated driving sessions using electroencephalogram, the Karolinska sleepiness scale, and visual analog scales. They found that young driver experienced a significant decrease in alertness and a strong tendency to sleep compared to middle-aged drivers. @wu2014using used the 100-Car Naturalistic Driving Study dataset and reported that drivers under the age of 25 were more likely to have crashes and safety-related events.

To meet the huge demand services and supply chain management, it is common to extend the retirement age or reemploy retired workers, especially in developing countries [@popkin2008age]. Aged drivers have an increased chance of driving safety issues for three reasons: impaired eyesight, prolonged reaction time to exogenous stimuli, and vulnerability to fatigue [@di2011demographic]. Aged drivers are associated with eyesight diseases or functionality impairment, such as cataracts, narrowed peripheral vision and decreasing visual acuity [@di2011demographic]. In addition, working for truck companies often means irregular shifts and taking the night schedules, which disrupt the circadian time-keeping systems, especially for the aged workers [@moneta1996time]. It is indicated by research that the "critical age" of shiftwork intolerance is about 45 to 50 years, at which sleep disorder, persisting fatigue and digestive problems become the most obvious [@di2011demographic].

Another risk factor for truck crashes at driver's level is gender. Gender has been suggested to be related with outcomes in medical treatment, education, sports and other fields, and there is no exception for truck drivers’ safety. In the first place, women are more likely to suffer from fatigue compared with men. @fjell2008perceived found that women in general have 1.4 times higher chance of complaining of fatigue than men. However, females are found to have longer sleeping hours than their male counterparts of the same race [@lauderdale2006objectively]. This study also found that the mean sleep hours for white females was 6.7 hours compared with 6.1 hours for white males, and 5.9 hours for black female compared with 5.1 hours for black males even after adjusting for socioeconomic status, lifestyle and sleep apnea [@lauderdale2006objectively]. Gender differences are huge in terms of working conditions. Females had significantly fewer working hours per week, with 47 hours versus 52 hours per week [@rotenberg2008gender]. In general, women tend to work fewer hours within a week but are more prone to feel fatigue and have a higher risk of traffic incidences.


### Traffic

Traffic characteristics are also viewed as an important risk factor for traffic safety issues. For the sake of availability and low cost, most prior studies used aggregated traffic data as proxies of traffic, such as Annual Average Daily Traffic (AADT). More recently, an increasing number of studies start to use real-time traffic data as a high-resolution proxy of traffic characteristics. Three published papers reviewed the impact of traffic variables on traffic safety issues [@wang2013effect; @theofilatos2014review; @roshandel2015impact].

Traffic variables include flow (traffic volume), occupancy/density, and speed [@wang2013effect; @theofilatos2014review]. Traffic flow is defined as the number of vehicles passing through a specific road segment in a given unit time. Traffic occupancy or density is defined as the number of vehicles in a unit area of road at a moment. Speed can be computed from the road perspective as the mean speed of vehicles passing that road segment (such as the AADT), or from the vehicle perspective as the speed of the vehicle (such as real-time speed). Compared to traffic flow and speed, traffic density is relatively less investigated due to a lack of relevant data.

For example, based on multinomial logit and negative binomial models, @dong2017estimating used vehicle and driver characteristics, traffic, environment, and road geometry to predict the frequency and severity of large truck-involved crashes. They found that the percent of large trucks, AADT, driver condition, and weather characteristics were significantly associated with both crash frequency and severity. @theofilatos2018impact used hourly aggregated traffic variables, including flow, occupancy, mean time speed, and percentage of trucks to predict crash occurence with a bias-correction logistic regression. This study found that the main risk factor, average speed had a negative effect on crashes. Instead of studying risk factors of crashes, @kamla2019analysing focused on the association between Hard Braking Incidents (HBIs) and geometric and traffic variables among large trucks at roundabouts. They found that HBIs were influenced by traffic and geometric variables in a similar fashion as crashes.

### Weather

Weather variables, including precipitation, visibility, wind speed, and temperature, have have reported to have both direct and indirect effects on traffic safety events. @theofilatos2014review provides a review on weather characteristics and road safety.

Real-time extreme weather conditions such as heavy rain, fog, storm, and snow can either impair the driver’s visual capability or reduce the safety of driving on the road [@baker1992wind; @chang2005data; @al2007experimental]. It is to noted that the cumulative time of driving in such extreme weather conditions could potentially increase the chances of safety critical events. The positive linear relationship between precipitation and traffic accidents can be observed in both driver accidents and pedestrian accidents [@al2007experimental; @graham2003spatial]. @naik2016weather used ordinal and multinomial regression models with random-effects to investigate crash severity under various weather conditions. They found that wind speed, rain, humidity, and temperature were associated with single-vehicle truck crashes. @abdel2012real used detector and sensor data to successfully predict more than 70% of accidents with low visibility conditions.

In addition, the increase of ambient temperature places risks on occupational safety, and possibly leads to cognition loss, heat stroke, and impairment of wakefulness. Previous evidence showed that the risk of mistakes and safety critical events increase in hot weather [@kjellstrom2009direct; @basagana2015high]. Leard and Roth found that for a day with temperature above 80 $^{\circ}$F, there is a 9.5% increase in fatality rates compared with a day at 50-60 $^{\circ}$F [@leard2015weather]. A literature review by @im2016impact found that 11 out of 13 studies indicated an increase in unintentional injuries associated with high temperatures. In constrast, when low temperature is present, truck drivers are likely to be faced with snowy or icy road conditions, as well as the presence of fog, which substantially increase the risk of driving [@lemp2011analysis]. For example, @ahmed2018effects reported that truck-involved crashes were 19% more likely to occur than no truck-involved crashes when snow or strong wind were present.

### Road characteristics

Based on engineering theory, it is expected that road characteristics are potential risk factors of road safety [@wang2013effect]. Commonly used road characteristics in traffic safety studies include the number of lanes, lane with, speed limits, horizontal curves, road curvature, and lighting conditions.

The effect of the number of lanes and lane with on traffic safety is inconsistent in previous literature. Some studies suggest that the number of lanes is negatively associated with the risk of traffic accidents. For example, @zhu2011comprehensive found that crashes on roadways with more lanes tended to be less severe, which may result from the fact that more lanes give more space and separation between vehicles. They also reported that crashes in higher speed limit segments were more likely to be severe crashes. In contrast, several other studies suggested that an increase in the number of lanes and lane width were positively associated with traffic fatalities [@noland2004effect; @kononov2008relationships; @zhu2011comprehensive; @islam2014comprehensive]. This reversed relationship could possibly be explained by an increased chance of lane-change-related conflict opportunities [@wang2013effect].

It is generally believed that lower speed limits can reduce the chances of traffic crashes, as well as the severity of crashes. For example, @neeley2009effect used state-level data from 1991 to 2005 to examine the association between truck-specific restrictions and fatality rates. They found that higher speed limits were associated with increased fatality rates, although different speed limits across vehicle types had no significant effect. Another study by @davis2015longitudinal also provided evidence that both overall and truck-involved fatalities were positively associated with maximum speed limits. 

Road geometric design features, such as road curvature and terrain type, were also reported to be risk factor of traffic safety events. @dong2015assessment used zero-inflated negative binomial models to examine the effects of road geometry fratures and crash frequency. Based on 1,787 truck-involved crashes from 1,310 highway segments in four years, they found that AADT, segment length, degree of horizontal curvature, terrain type, land use and width, median type, right side shoulder width, lighting condition, rutting depth, and posted speed limits were significantly associated with the likelihood of truck-involved crash frequency. @islam2014comprehensive found that crashes on roadway curved were associated with higher likelihood of major and possible injuries in urban single-vehicle large truck at-fault accidents, but this association is not statistically significant in multi-vehicle accidents.

<!-- 
@uddin2017truck lighting conditions. 
@meuleners2017determinants lighting conditions.  

-->