Analytical Plan for Aim 1
-------------------------

The first aim seeks to determine the association between the rate of crashes and the rate of SCEs at the level of drivers. The cohort will be all drivers with at more than 100 pings. Drivers with less than 100 real-time pings will be recognized as potential outliers and excluded from analysis.

### Data reduction

In order to make the MCMC estimation for Bayesian models tractable, I will use the following data reduction algorithms to aggregate real-time ping data to *trips* and *shifts*:

- For each of the truck drivers, if the real-time ping data showed that the truck was not moving for more than 20 minutes, the ping data will be separated into two different *trips*.
- These trips data will be further divided into different *shifts* if the specific driver was not moving for eight hours. 

Therefore, a *trip* is defined as a continuous period of driving without stopping for more than 20 minutes. a *shift* is defined as a long period of driving without stopping for more than 8 hours. 

### Outcome and predictor variables

The outcome variable will be the number of crashes for each driver. The primary independent variable will be the number of SCEs per 10,000 miles. These SCEs will be further decomposed into the number of hard brakes, headways, and rolling stability per 10,000 miles in similar analysis. The covariates will be the total miles driven, the percent of night driving, and the age of the drivers.

### Statistical models

Since the outcome variable is a count variable, a Poisson model or a negative binomial model is a natural choice for this type of outcome variable [@lord2010statistical]. However, these two models are less likely to fully account for the variance across drivers. Therefore, I propose to use a Gamma-Poisson model to examine the association between crashes and SCEs. Here is how the proposed Gamma-Poisson model will be implemented:

Let us assume that:
$$
\begin{aligned}
\lambda & \sim \text{Gamma}(\alpha, \beta)\\
X|\lambda & \sim \text{Poisson}(\lambda)\\
\end{aligned}
$$
Then we have:
$$X \sim \text{Gamma-Poisson}(\alpha, \beta)$$
The Gamma-Poisson distribution is a $\alpha$-parameter distribution, with the $\alpha$ as a measure of overdispersion. The Gamma-Poisson distribution  has the probability mass function of:
$$f(x) = \frac{\Gamma(x + \beta)\alpha^x}{\Gamma(\beta)(1 + \alpha)^{\beta + x}x!}, \quad x = 0, 1, 2, \dots$$

The mean and variance of a Gamma-Poisson distribution are:
$$
\begin{aligned}
E(X) & = \alpha\beta \\
V(X) & = \alpha\beta + \alpha^2\beta\\
     & = \alpha\beta(1 + \alpha)
\end{aligned}
$$

The log-linear Gamma-Poisson model will be specified as:
$$
\log\beta = \mathbf{X\gamma} - \log m,
$$
where $\mathbf{X}$ is the predictor variables matrix, including the percent of night driving and the age of the drivers, $\mathbf{\gamma}$ is the associated $2*1$ parameter vector, $m$ is the total miles driven as an offset term in the Poisson distribution, and $\alpha$ is a fixed overdispersion parameter that does not depend on any covariates.

All data reduction, cleaning, and statistical analysis will be done on the RStudio Server on the Ohio Supercomputer Center (OSC). The OSC provides high performance computing resources and expertise to academic researchers [@OSC1987]. The Bayesian statistical models will be conducted using the `rstan` package in R 3.5.1 [@rstancitation; @Rcitation].