# THREE MODELS

## Hierarchical logistic model

### Model set up


### Bayesian estimation based on simulated data


## Hierarchical Poisson model




## Hierarchical power law process

*Mean function of a point process**: 

$$\Lambda(t) = E(N(t))$$

$\Lambda(t)$ is the expected number of failures through time $t$.

**Rate of Occurence of Failures (ROCOF)**: When $\Lambda$ is differentiable, the ROCOF is:

$$\mu(t) = \frac{d}{dt}\Lambda(t)$$
The ROCOF can be interpreted as the instantaneous rate of change in the expected number of failures.

**Intensity function**: The intensity function of a point process is 

$$\lambda(t) = \lim_{\Delta t \rightarrow 0}\frac{P(N(t, t+\Delta t] \geq 1)}{\Delta t}$$

When there is no simultaneous events, ROCOF is the same as intensity function.


**Nonhomogeneous Poisson Process (NHPP)**: The NHPP is a Poisson process whose intensity function is non-constant.

**Power law process (PLP)**: When the intensity function of a NHPP is:

$$\lambda(t) = \frac{\beta}{\theta}\bigg(\frac{t}{\theta}\bigg)^{\beta-1}$$
Where $\beta > 0$ and $\theta > 0$, the process is called the power law process (PLP).

Therefore, the mean function $\Lambda(t)$ is the integral of the intensity function:

$$\Lambda(t) = \int_0^t \lambda(t)dt = \int_0^t \frac{\beta}{\theta}\bigg(\frac{t}{\theta}\bigg)^{\beta-1} = \bigg(\frac{t}{\theta}\bigg)^{\beta}$$




### 


### Bayesian estimation based on simulated data